# Generated by Django 2.2.2 on 2020-07-11 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200709_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cell_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Contact cell phone number. Add '+385' in front for Croatia.", max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Contact phone number. Add '+385' in front for Croatia.", max_length=128, region=None),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['latitude', 'longitude'],
            },
        ),
    ]
