# Generated by Django 2.2.2 on 2020-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200711_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='time'),
        ),
    ]
